# Generated by Django 4.0.5 on 2024-05-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_estudiantil', models.CharField(max_length=9, unique=True)),
                ('lugar_nac', models.CharField(max_length=200)),
                ('literal', models.CharField(max_length=100)),
                ('grado', models.IntegerField()),
                ('repite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='info_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('fec_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('P', 'Papá'), ('M', 'Mamá'), ('T', 'Tio(a)'), ('A', 'Abuelo(a)'), ('H', 'Hermano(a)')], max_length=2)),
                ('fk_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.persona')),
            ],
        ),
        migrations.CreateModel(
            name='tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camisa', models.CharField(max_length=150)),
                ('pantalon', models.CharField(max_length=150)),
                ('estatura', models.CharField(max_length=9, unique=True)),
                ('peso', models.IntegerField()),
                ('fk_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_info_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.info_contacto')),
                ('fk_relacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.relacion')),
            ],
        ),
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.estudiante')),
                ('fk_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.relacion')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fk_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.persona'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fk_representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.representante'),
        ),
        migrations.CreateModel(
            name='enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=150)),
                ('fk_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.estudiante')),
            ],
        ),
    ]
