# Generated by Django 3.2.16 on 2024-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_auto_20240526_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='repite',
            field=models.BooleanField(default=False),
        ),
    ]
