# Generated by Django 3.2.16 on 2024-05-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_alter_estudiante_repite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacion',
            name='fk_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.persona'),
        ),
    ]
