# Generated by Django 3.2.16 on 2010-05-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_alter_relacion_fk_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallas',
            name='fk_estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fk_tallas',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='escuela.tallas'),
            preserve_default=False,
        ),
    ]
