# Generated by Django 3.2.16 on 2010-05-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_auto_20100506_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='literal',
        ),
    ]
