# Generated by Django 3.2.16 on 2010-05-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
